spring:
  application:
    name: telegram-trading-bot
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trading_db} # URL ??????????? ? ???? ??????
    username: ${DB_USERNAME:postgres} # ??? ???????????? ??? ??????????? ? ???? ??????
    password: ${DB_PASSWORD:postgres} # ?????? ??? ??????????? ? ???? ??????
    hikari:
      pool-name: ${CONNECTION_POOL_NAME:Legram Template} # ??? ???? ?????????? HikariCP
      minimum-idle: ${MINIMUM_IDLE:5} # ??????????? ?????????? ???????????, ??????? ????? ?????????? ? ????????
      maximum-pool-size: ${MAXIMUM_POOL_SIZE:10} # ???????????? ?????????? ?????????? ? ????
      schema: ${DB_SCHEMA:public} # ????? ???? ?????? ?? ?????????
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  flyway:
    enabled: true # ????????? Flyway ??? ???????? ???? ??????
    baseline-on-migrate: true # ????????? ??????? ?????? ??? ????????
    locations: classpath:db/migration # ???? ? ?????? ????????
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trading_db} # URL ??????????? ? ???? ?????? ??? Flyway
    user: ${DB_USERNAME:postgres} # ??? ???????????? ??? ??????????? ? ???? ?????? ??? Flyway
    password: ${DB_PASSWORD:postgres} # ?????? ??? ??????????? ? ???? ?????? ??? Flyway
    schemas: ${DB_SCHEMAS:public} # ????? ???? ??????, ??????? ?????? ???? ???????????

telegram:
  bot:
    username: ai_trading_pm_bot
    token: 8381514401:AAGTpC3FFHFUrsMD_Cx_ZVzGGQzXoU4tTPQ

ml:
  api:
    url: https://decision-agent-trading-bot.onrender.com


finnhub:
  api:
    key: d4qmrm1r01quli1dlllgd4qmrm1r01quli1dllm0